### ISSUE TITLE
Some questions about coordination transformation

### ISSUE THREAD

**Issue by maobenz** [facebookresearch/neuralvolumes#8]
Hello,
Thanks for releasing your code. I am impressed by your work. Now I hope to run your code with my our dataset. I have two questions.

Firstly, I see the pose.txt is used in the code to put the objects in the center. If I use my own data, will the file still work?

Secondly, I see the code set the raypos is among -1 and 1. Is it the matrix in this pose file that narrows the range to -1 to 1? My own dataset' range is different.

Thirdly, does the code limit the scope of the template? Does it have to be between 0-255?

Thanks a lot in advance!

**Comment by stephenlombardi** [comment]
1. No, you need to create your own pose.txt. See this comment for a little more information on the pose.txt file: https://github.com/facebookresearch/neuralvolumes/issues/1#issuecomment-591602762

2. There's two parts to it, basically. The pose.txt will center the scene so that [0,0,0] is near the center of the object. There's also a worldscale parameter that's passed to the dryice dataset class that scales the coordinates down so that they're in [-1, 1]. 

3. There's no limit to the range of the template, it can be any non-negative floating point values.

-- Steve

**Comment by maobenz** [comment]
Thanks! I have another question about the fixedimage. Could i feed different images with different views at every iterations? My dataset has many different views and i can confirm every time i will feed images with the same motion but different views, not only fixed 3 or 4 views.

**Comment by stephenlombardi** [comment]
You could feed different views to the fixedimage but I would guess it would degrade performance a bit. It's also possible you would need to adjust the learning rate a bit to deal with the additional variation in input data. I'm not sure though as I haven't tried it.
